"""empty message

Revision ID: 0e61b7d7b123
Revises: 63b782da804c
Create Date: 2025-11-22 09:50:38.387296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e61b7d7b123'
down_revision = '63b782da804c'
branch_labels = None
depends_on = None


def upgrade():
    # 1) Set all existing NULL login_attempts to 0
    op.execute("UPDATE users SET login_attempts = 0 WHERE login_attempts IS NULL;")

    # 2) Now alter the column to be NOT NULL safely
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'login_attempts',
            existing_type=sa.INTEGER(),
            nullable=False
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
